### ISSUE TITLE
FT Logo is uneven

### ISSUE THREAD

**Issue by hamadyne** [flawlessly-taboo/regal-foundation#1]
While making a proper PSD file I noticed that the FT logo is made really unevenly. This could be remade to look more professional.

**Comment by zombiflux** [comment]
Go ahead and remake it professionally with transparency and we can present it to Kris

**Comment by zombiflux** [comment]
![ftlogo_vector](https://cloud.githubusercontent.com/assets/26048663/23693945/c910c05a-039c-11e7-9559-214fd11e2794.png)
 Any better? I sent a copy to Kris as well. Let me know what you think and any possible improvements. Also made a rose colored version for the site that is in the repo now.

**Comment by hamadyne** [comment]
Looks much better. Feel free to send this over to Kris for review.

**Comment by zombiflux** [comment]
Kris approves of and loves the logo cleanup, as well as the alternate pink logo. I gave her copies to use and the new version looks much cleaner. Kris has no further requests for logo improvements. If you have no improvements to add or request, please close this issue.
