### ISSUE TITLE
Product Item Pages

### ISSUE THREAD

**Issue by zombiflux** [flawlessly-taboo/regal-foundation#10]
Kristina wants each item for sale to have its own product page that pops up when you click on the product. The product page will have the following:

Several pictures of the products from different angles that can be scrolled through.

Product description. Size selector/price (add to cart functionality) along with the size chart. This was just mentioned to me as I was setting up cloudhosted.

**Comment by zombiflux** [comment]
The sets page also needs a selector per set to choose what style bottom panties

**Comment by hamadyne** [comment]
With the current way the JS is set up I can't make the pricing show up on the popup, but I can make a small gallery with different views for each product and a short description. 

Need descriptions for products; we have the alt images for the gallery.

I was not aware there was a different selector needed for the "Sets" page. Might not have time to complete this feature at release.

**Comment by hamadyne** [comment]
Sets now have their a custom panty selector.

**Comment by hamadyne** [comment]
Content for Boxer, Gaff, and Sissy have been added.

**Comment by hamadyne** [comment]
Size Selectors and price updates now appear. 
Clicking on the product photos opens up a slideshow that features all product images (including front+back images)
