### ISSUE TITLE
Constrain Proportions on Carousel

### ISSUE THREAD

**Issue by zombiflux** [flawlessly-taboo/regal-foundation#11]
The carousel on the front page needs the proportions constrained so that when the window is resized the carousel keeps it's size ratio and doesn't skew or squish.

**Comment by hamadyne** [comment]
Might be too much for mobile. Would be a better design choice to use a static image. Will attempt to find solution in the meantime.

**Comment by hamadyne** [comment]
Removed carousel visibility, static image to be created later.
