### ISSUE TITLE
About Us Text Wrapping

### ISSUE THREAD

**Issue by zombiflux** [flawlessly-taboo/regal-foundation#2]
The two blocks of text for the about us page do not line up, and Kristina would like them too. I put the signature text
 "XOXO,
Kristina Arnold
Owner and Designer
Flawlessly Taboo"
in a new div so the pink lips, which she likes and wants to keep, can be in the background behind the signature block and that block only. Which means I have to do seperate align attributes. Is there a way the code can be fixed so that the text next to the picture doesn't wrap under the picture and stays in line with the block underneath? And can you realign the lips background for the wrap div (that has the signature) to be more behind the signature?

**Comment by hamadyne** [comment]
Lined up text and image blocks (see . 
Lips now positioned behind signature. (NOTE: Image positioning makes text difficult to read, could use new position and/or image)
