### ISSUE TITLE
Hot Products Carousel needs visual redesign

### ISSUE THREAD

**Issue by zombiflux** [flawlessly-taboo/regal-foundation#3]
Kris is not a fan of the semi-transparent gray background or 'side margins' on the carousel, and neither am I. Wondering if we can make the background go away and you just see the various images as they cycle through. Also keep the pink arrows but make them closer to the image so it looks tighter visually.

**Comment by hamadyne** [comment]
Removed transparent gray background. Side button controls are intact, with additional pink buttons on the bottom of the carousel for alternative navigation.

New carousel CSS uses un-colorable icons for prev/next buttons, will look for alternative that we can color pink.

Found that landscape images are much easier to position than portrait images. Requesting that future images be provided in this manner.

**Comment by zombiflux** [comment]
Carousel needs "Hot Products" or "Hot Now" banner/title visible somewhere, as per Kris's specs. Kris also preferred pink arrows from old carousel (but rest of new carousel is preferred). When product catalog is added, the product pictures need to link to corresponding products.
