### ISSUE TITLE
Website Footer Needed

### ISSUE THREAD

**Issue by zombiflux** [flawlessly-taboo/regal-foundation#4]
A footer for just the main content area on every page needs to be added. It should just be a white strip locked into the bottom (fixed) so when you scroll through the main content the footer stays on screen at the bottom. Kris wants it plain white with small text displaying the following:

Copyright Flawlessly Taboo 2017. Contact Us: flawlesslytaboo@gmail.com Terms of Agreement

The terms of agreement will link to a plain webpage or .pdf that has the following document: 
https://www.flawlesslytaboo.com/terms-of-agreement

And if we ever get sites for our own portfolios, we are welcome to make a small and unobtrustive link at the end of the footer: Site designed by Amanda O'Donnell (hotlink) and Tyler Thomas (hotlink)

**Comment by hamadyne** [comment]
Adding a white-colored footer breaks the background and sidebar pattern. See latest build at [commit 9d182f0e.](https://github.com/flawlessly-taboo/regal-foundation/commit/9d182f0e4758cf89d897e5df1036202229befeb7)
