### ISSUE TITLE
Category Changes

### ISSUE THREAD

**Issue by zombiflux** [flawlessly-taboo/regal-foundation#7]
Kris needs the "splitback" category changed/renamed to "Peek-a-boo". I can do it in the text but files should be renamed and redirected. The following category pages also need to be added: Gaff, G-String, Sissy

The product dropdown for desktop also needs to scroll or its too long to see all categories

**Comment by zombiflux** [comment]
Boxers also needs to be a category

**Comment by hamadyne** [comment]
Are there images for these additional categories? If not we'll have blank pages.

**Comment by hamadyne** [comment]
Categories added, imaged to be provided by Kris when she's able.
