### ISSUE TITLE
New Item Sizes and Price Calculation

### ISSUE THREAD

**Issue by zombiflux** [flawlessly-taboo/regal-foundation#9]
The sizes on the drop down for items for sale need to have the options: Small, Medium, Large, X-Large, 2X, 3X, 4X, 5X. 2X-5X will have an upcharge on the price depending on the product.

**Comment by hamadyne** [comment]
Need calculations for pricing or else I can't finish this section.

**Comment by hamadyne** [comment]
New pricing has been added, now just needs new way to calculate price based on sizing/set choice.

**Comment by hamadyne** [comment]
Prices now update based on sizing/set choice. May require future changes, fur the base functionality is there now.
